//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itqan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Withme
    {
        public int ID_contact { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> id_define { get; set; }
        public Nullable<int> Lang { get; set; }
    
        public virtual Define_Itqan Define_Itqan { get; set; }
        public virtual Lang1 Lang1 { get; set; }
    }
}
