//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itqan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItqanEntities : DbContext
    {
        public ItqanEntities()
            : base("name=ItqanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card_Feture> Card_Feture { get; set; }
        public virtual DbSet<Categore_People> Categore_People { get; set; }
        public virtual DbSet<Condition> Condition { get; set; }
        public virtual DbSet<Contact_Withme> Contact_Withme { get; set; }
        public virtual DbSet<Content_course> Content_course { get; set; }
        public virtual DbSet<Feture_Itqan> Feture_Itqan { get; set; }
        public virtual DbSet<Goals> Goals { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Plan_Studie> Plan_Studie { get; set; }
        public virtual DbSet<Police> Police { get; set; }
        public virtual DbSet<Required_IT> Required_IT { get; set; }
        public virtual DbSet<Service_anther> Service_anther { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Why_Itqan> Why_Itqan { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<IMAGE_header> IMAGE_header { get; set; }
        public virtual DbSet<Lang1> Lang1 { get; set; }
        public virtual DbSet<Define_Itqan> Define_Itqan { get; set; }
        public virtual DbSet<Alnoor> Alnoor { get; set; }
        public virtual DbSet<FirstContentQuran> FirstContentQuran { get; set; }
        public virtual DbSet<App> App { get; set; }
    }
}
