//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itqan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_anther
    {
        public int ID_Services { get; set; }
        public string Services { get; set; }
        public string Descreption_services { get; set; }
        public string IMG_Services { get; set; }
        public string link_services { get; set; }
        public Nullable<int> id_define { get; set; }
    
        public virtual Define_Itqan Define_Itqan { get; set; }
    }
}
