// <auto-generated />
namespace Itqan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ItqanModelsItqanEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItqanModelsItqanEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202110161328191_Itqan.Models.ItqanEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
