// <auto-generated />
namespace Itqan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ItqanModelsItqanEntitiesyt1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItqanModelsItqanEntitiesyt1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110191915116_Itqan.Models.ItqanEntities-yt1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
