//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itqan.Ressourse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itqan.Ressourse.resourse", typeof(resourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن إتقان.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورات.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم، والمنصة تدعم ذلك وتؤيده على ألا يؤثر ذلك على سير الدرس..
        /// </summary>
        public static string AnswerCan {
            get {
                return ResourceManager.GetString("AnswerCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم، إذا توفَّر معلِّم آخر يجيد لغة الطالب فإن المنصة تتيح للطالب تغيير المعلم..
        /// </summary>
        public static string AnswerInst {
            get {
                return ResourceManager.GetString("AnswerInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لدينا معلمون مؤهلون ومتقنون يتحدثون بلغتك ولديهم شهادة في تدريس القاعدة النورانية، ويملكون الخبرة في تدريس القرآن الكريم والتدريس عن بعد..
        /// </summary>
        public static string AnwerInst {
            get {
                return ResourceManager.GetString("AnwerInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بماذا تتميز منصة اتقان.
        /// </summary>
        public static string benifits {
            get {
                return ResourceManager.GetString("benifits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل يستطيع ولي الأمر حضور الجلسة التعليمية مع الطفل؟.
        /// </summary>
        public static string CanFather {
            get {
                return ResourceManager.GetString("CanFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات المستهدفة.
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والاحكام.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string contactwithme {
            get {
                return ResourceManager.GetString("contactwithme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برامجنا.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Detiles {
            get {
                return ResourceManager.GetString("Detiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزايا اتقان.
        /// </summary>
        public static string feturs {
            get {
                return ResourceManager.GetString("feturs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاهداف.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف أسجل في المنصة.
        /// </summary>
        public static string how {
            get {
                return ResourceManager.GetString("how", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  هل أستطيع تغيير المعلم؟.
        /// </summary>
        public static string HowChange {
            get {
                return ResourceManager.GetString("HowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من هم معلمو المنصة؟.
        /// </summary>
        public static string HowIns {
            get {
                return ResourceManager.GetString("HowIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راجع شروط التسجيل.
        /// </summary>
        public static string howReg {
            get {
                return ResourceManager.GetString("howReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منصة اتقان.
        /// </summary>
        public static string Itqan {
            get {
                return ResourceManager.GetString("Itqan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجلسة التعليمية.
        /// </summary>
        public static string lecture {
            get {
                return ResourceManager.GetString("lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روابط تهمك.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد.
        /// </summary>
        public static string Moor {
            get {
                return ResourceManager.GetString("Moor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطط الدراسة.
        /// </summary>
        public static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة  منصة إتقان 2021.
        /// </summary>
        public static string Privace {
            get {
                return ResourceManager.GetString("Privace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القاعدة النورانية.
        /// </summary>
        public static string Quaida {
            get {
                return ResourceManager.GetString("Quaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القاعدة النورانية.
        /// </summary>
        public static string qudiah {
            get {
                return ResourceManager.GetString("qudiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القران الكريم.
        /// </summary>
        public static string Quran {
            get {
                return ResourceManager.GetString("Quran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل معنا.
        /// </summary>
        public static string registerwithus {
            get {
                return ResourceManager.GetString("registerwithus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التسجيل.
        /// </summary>
        public static string RegistrationTerms {
            get {
                return ResourceManager.GetString("RegistrationTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتطلبات التقنية.
        /// </summary>
        public static string requiredIT {
            get {
                return ResourceManager.GetString("requiredIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string sendbutton {
            get {
                return ResourceManager.GetString("sendbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنهج التعليمي وطريقة الدراسة.
        /// </summary>
        public static string Sesion {
            get {
                return ResourceManager.GetString("Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة النبوية.
        /// </summary>
        public static string Sunah {
            get {
                return ResourceManager.GetString("Sunah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرؤية.
        /// </summary>
        public static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماهي شروط التسجيل.
        /// </summary>
        public static string WhatCondition {
            get {
                return ResourceManager.GetString("WhatCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لماذ منصة اتقان.
        /// </summary>
        public static string why {
            get {
                return ResourceManager.GetString("why", resourceCulture);
            }
        }
    }
}
